### ISSUE TITLE
Synchronize modules/ directory naming system to MIDCA's theory

### ISSUE THREAD

**Issue by dtdannen** [COLAB2/midca#1]
The purpose of this issue is to synchronize naming conventions of files under the modules/ directory to correspond to the names of Phases in the MIDCA theory (of which there are six) - this makes it easy for people to read a research paper on MIDCA and quickly identify where the phases are implemented in the code base.

Most module classes are located in a file named by the phase that module is used in: for example PyHopPlanner module is located in the planning.py file corresponding to the planning phase. Currently there is no interpret.py file, instead modules belonging to Interpret phase are located in three different python files note.py, assess.py, and guide.py. This is confusing for new folks joining the project since note assess guide is not referenced anywhere else. Interpret is a large phase conceptually because discrepancy detection (analogous to Note), explanation (analogous to assess) and guide (analogous to goal formulation) all happen within Interpret.

I propose that we make the modules folder contain six sub folders for each theoretical midca phase, so like:

modules/perceive/
modules/interpret/
modules/evaluate/
modules/intend/
modules/plan/
modules/act/

then when importing files, its easy to see what modules are available for each phase because we import like:

from modules.interpret.goal_formulation import SimpleGoalGen

This would also include changing note.py to discrepancy_detection.py, assess.py to explanation.py, and guide.py to goal_generation.py.

**Comment by mcox25** [comment]
I agree with these comments. Can we go ahead and implement the changes, or is the reason we have waited 11 months on this is because it entails a big side effects and associated code changes?

**Comment by dtdannen** [comment]
I haven't looked in a while, but I don't believe this should cause drastic changes and shouldn't be hard to implement - it is mostly refactoring. I think the long delay is just because no one got around to it (including myself).
