### ISSUE TITLE
util.py doesn't handle all operators

### ISSUE THREAD

**Issue by Shree9** [COLAB2/midca#11]
midca/domains/blocksworld/util.py: pyhop_tasks_from_goals method doesn't cover all the predicates and operators, the method will break for the "putdown" operator and possibly other operators too. unsure if this happens for other domain's util.py files. 
<img width="753" alt="Screen Shot 2020-10-23 at 10 58 34 AM" src="https://user-images.githubusercontent.com/25558530/97019754-b4b69980-151e-11eb-86cd-4e0658c15e8d.png">

**Comment by mcox25** [comment]
Any movement on this issue?

**Comment by Shree9** [comment]
Issue resolved: mistaken operators to goals.
